/*MENU COMPROBANTES

-----INIT SOLICITUD
FRONTEND: comprobantes:get
-----ENVIO A FRONT RETAIL 
BACKEND: comprobantesGetFR
-----ENVIO RESPUESTA DE FRONT RETAIL A BACKEND
FRONT RETAIL: comprobantes:get:fr:response
-----ENVIO SOLICITUD A SERVIDOR BACKUP
BACKEND: comprobantesGetSBK
-----ENVIO RESPUESTA DE SERVIDOR BACKUP A BACKEND
SERVIDOR BACKUP: comprobantes:get:sbk:response
-----ENVIO RESPUESTA A FRONTEND
BACKEND: comprobantes:get:response


*/